### ISSUE TITLE
Doesn't refresh when the page changes

### ISSUE THREAD

**Issue by mokhosh** [Te7a-Houdini/alpinejs-devtools#14]
related https://github.com/Te7a-Houdini/alpinejs-devtools/issues/1 but different

**Comment by Te7a-Houdini** [comment]
@mokhosh can you provide more details on this issue .

**Comment by mokhosh** [comment]
For example if I'm on the homepage with the dev tools open, and I click on the login link, when the page changes, the dev tools still shows the components from homepage, not the login page.

**Comment by Te7a-Houdini** [comment]
@mokhosh ok got it thanks a lot for the explanation

**Comment by mokhosh** [comment]
Thank you a lot for the extension :)

**Comment by ryangjchandler** [comment]
I'm going to suggest we move this dicussion over to #1 since it's all down to the same problem and IIRC will have the same solution.

**Comment by Te7a-Houdini** [comment]
@ryangjchandler  ok :+1:

**Comment by ryangjchandler** [comment]
Discussion moved to #1, closing issue :)
