### ISSUE TITLE
Enhancement: move build, tests and publishing process to workflow

### ISSUE THREAD

**Issue by ryangjchandler** [Te7a-Houdini/alpinejs-devtools#15]
Not a major one obviously but I think it's nice to have the process automated where possible to reduce friction.

I'm thinking run tests, build and publish on a release / tag. Should be possible, haven't looked into it yet though.

**Comment by HugoDF** [comment]
Sure, we might need some tests first 🙈🙈🙈.

For now maybe just run the build in a GitHub action? Would help catch really obvious errors in PRs

**Comment by ryangjchandler** [comment]
> Sure, we might need some tests first 🙈🙈🙈.
> 
> For now maybe just run the build in a GitHub action? Would help catch really obvious errors in PRs

Yeah, no tests yet but we will need some soon haha! Agreed, I'll throw in a separate PR for this after the Rollup one is done and merged.

**Comment by HugoDF** [comment]
On reflection, this might need to be tackled sooner rather than later

At the very least, we need merges to master to bump the version so we can republish (the new version) to Firefox and Chrome extension stores.

**Comment by ryangjchandler** [comment]
I don't think we should bump version on every merge to master, rather run test (when we have some). I think we should get a workflow for releasing, so when we tag it automatically does it for us. Would be nice to have that for 0.0.2

**Comment by HugoDF** [comment]
How do you mean? Run the build on CI so that & save the output so that we've got a releasable artifact?

**Comment by ryangjchandler** [comment]
> How do you mean? Run the build on CI so that & save the output so that we've got a releasable artifact?
> 
> I agree re-bumping

Yeah exactly that - there's a GitHub Action for it somewhere

**Comment by HugoDF** [comment]
Should we split out the "how do we test this?" to a separate issue?

I've got some ideas around how we could do it.

**Comment by ryangjchandler** [comment]
Yeah sounds like a good shout.

**Comment by HugoDF** [comment]
whoops not that PR solved everything in this issue, but I think this is as far as we're going to get with automation since publishing is a manual process (although it's easy with the build artifacts we have now)

so we've got:

- test
- build
- creation of downloadable archive that can be used to submit to FF addon gallery
