### ISSUE TITLE
Add (Firefox) screenshots

### ISSUE THREAD

**Issue by HugoDF** [Te7a-Houdini/alpinejs-devtools#19]
Feedback on submission of `0.0.1` to Firefox Add-ons Gallery was that a longer description + some action screenshots would likely be beneficial to the listing.

**Comment by ryangjchandler** [comment]
Same can probably be applied to the Chrome extension as well.

**Comment by HugoDF** [comment]
> Same can probably be applied to the Chrome extension as well.

😄 yeah that's why "(Firefox)" 👍
