### ISSUE TITLE
Keyboard shortcuts/input blur to save/cancel when editing a data property

### ISSUE THREAD

**Issue by HugoDF** [Te7a-Houdini/alpinejs-devtools#24]
When I'm editing a data property:

- pressing ESC should "cancel" my editing (reset to value before editing) - same as clicking the X icon
- pressing ENTER should "save" my edits (update value in Alpine app) - same as clicking the ✅ icon
- blurring the input should "cancel" my editing (reset to value before editing) - as per Vue Devtools implementation

**Comment by ryangjchandler** [comment]
> When I'm editing a data property:
> 
> * pressing ESC should "cancel" my editing (reset to value before editing) - same as clicking the X icon
> * pressing ENTER should "save" my edits (update value in Alpine app) - same as clicking the ✅ icon

Agreed, clicking outside of the field should save too I think..

**Comment by HugoDF** [comment]
@ryangjchandler I checked Vue Devtools, they cancel on blur but have updated.

**Comment by ryangjchandler** [comment]
> @ryangjchandler I checked Vue Devtools, they cancel on blur but have updated.

Maybe follow that behaviour then? I'm not sure

**Comment by ryangjchandler** [comment]
I'm happy to work on this one btw @HugoDF , you've done quite a bit today! :)

**Comment by HugoDF** [comment]
Cool!

**Comment by HugoDF** [comment]
@ryangjchandler I'm gonna pick this up now 😄
