### ISSUE TITLE
Name Elements

### ISSUE THREAD

**Issue by repat** [Te7a-Houdini/alpinejs-devtools#28]
As mentioned in the discourse chat:

It would be cool though if the `div`s on the left side would pull the `id` property (or something else) from the main/parent (the same where `x-data` is defined), so they're easier to tell apart.

If that's possible?

![image](https://user-images.githubusercontent.com/516807/79783420-bc8d5980-8394-11ea-8dcf-86ea961ebe49.png)

**Comment by HugoDF** [comment]
As I mentioned on the Discord the logic could be something like (in order of precedence):

- x-data's "function" name (if it's using `x-data="componentName()"` syntax)
- element with x-data's "name" attribute (if present) eg. `<div x-data="{} name="component"></div>`
- element with x-data's "role" (aria role) attribute (if present) eg. `<div x-data="{}" role="alert"></div>` -> `alert`
- element with x-data's "id" (if present) eg. `<div id="component" x-data="{}"></div>` -> `component`
- element with x-data's tagName (current behaviour) eg. `<div x-data="{}"></div>` -> `DIV`

**Comment by repat** [comment]
Hm, the way I just used it, I had one `data()` function but many components (looped with Laravels/Blades `@foreach`), the same way you would loop over a custom Vue `<component>`.
In this case it would be better if it's either `name` or `id` since they need/should to be different on each element but can use the same function

**Comment by ryangjchandler** [comment]
I think the `id` attribute should always take precedence, since this will (or should) always be unique.

**Comment by HugoDF** [comment]
> I think the `id` attribute should always take precedence, since this will (or should) always be unique.

Agree, moved is and name as first in precedence 🙂

**Comment by HugoDF** [comment]
Do we agree with this order @ryangjchandler @Te7a-Houdini @repat https://github.com/Te7a-Houdini/alpinejs-devtools/issues/28#issuecomment-616719252 ?

**Comment by ryangjchandler** [comment]
Yeah, I think this order makes the most sense - are we going to use selector style representation so `#id` for Id, `[name=""]` for name etc?

**Comment by HugoDF** [comment]
> Yeah, I think this order makes the most sense - are we going to use selector style representation so `#id` for Id, `[name=""]` for name etc?

I like this

**Comment by Te7a-Houdini** [comment]
@HugoDF ok i agree with that :+1:

**Comment by HugoDF** [comment]
I'm working on getting this pushed out today

**Comment by HugoDF** [comment]
> Yeah, I think this order makes the most sense - are we going to use selector style representation so `#id` for Id, `[name=""]` for name etc?

:eyes: I didn't end up doing this, do we feel strongly about it @ryangjchandler , should be easy enough to do as a follow-on PR

**Comment by ryangjchandler** [comment]
I'm not fussed either way to be honest. It's not a big deal, more of a natural look I suppose, not make or break :)
