### ISSUE TITLE
Release v0.0.2 to Chrome & Firefox

### ISSUE THREAD

**Issue by HugoDF** [Te7a-Houdini/alpinejs-devtools#31]
@Te7a-Houdini @ryangjchandler are we happy pushing an update out now?

The changelog is [here](https://github.com/Te7a-Houdini/alpinejs-devtools/milestone/1?closed=1):

- https://github.com/Te7a-Houdini/alpinejs-devtools/issues/26
- https://github.com/Te7a-Houdini/alpinejs-devtools/issues/13
- https://github.com/Te7a-Houdini/alpinejs-devtools/issues/6

I can submit a PR that bumps the versions & send it off to Firefox to review.

- [x] version bumped
- [x] create release https://github.com/Te7a-Houdini/alpinejs-devtools/releases/tag/0.0.2
- [x] release to Firefox https://addons.mozilla.org/en-GB/firefox/addon/alpinejs-devtools/
- [ ] release to Chrome

**Comment by ryangjchandler** [comment]
Yeah for sure, I'm happy - quite a few bug fixes and features.

**Comment by Te7a-Houdini** [comment]
@HugoDF yup am ok with that

**Comment by HugoDF** [comment]
@Te7a-Houdini if you can submit what's on master to Chrome I'll submit for Firefox

**Comment by Te7a-Houdini** [comment]
@HugoDF doing that now :+1:

**Comment by Te7a-Houdini** [comment]
@HugoDF there's a small bug i found that when clicking on the arrow to close the object it's not closed

**Comment by HugoDF** [comment]
@Te7a-Houdini oops, let's fix it 😄 

I created 0.0.2 release https://github.com/Te7a-Houdini/alpinejs-devtools/releases/tag/0.0.2

**Comment by Te7a-Houdini** [comment]
@HugoDF sure am currently away from labtop but just wanted to mention you quickly before submitting for review :joy:

**Comment by HugoDF** [comment]
Can be 0.0.3 then

**Comment by Te7a-Houdini** [comment]
sure

**Comment by HugoDF** [comment]
Released to Firefox Addons https://addons.mozilla.org/en-GB/firefox/addon/alpinejs-devtools/

**Comment by HugoDF** [comment]
due to a Firefox add on review, will be releasing 0.0.3 shortly
