### ISSUE TITLE
Feature Request: Firefox Extension

### ISSUE THREAD

**Issue by HugoDF** [Te7a-Houdini/alpinejs-devtools#4]
Thanks for putting this together.

Any idea how difficult it would be to port the extension to Firefox?

I'm happy to contribute something along those lines.

**Comment by Te7a-Houdini** [comment]
thanks a lot @HugoDF . i didn't investigate yet how firefox extensions work. so if you find a good approach to port the devtools to firefox  that would be great

**Comment by HugoDF** [comment]
@Te7a-Houdini from the vue-devtools repo, it seems like they're using the "shell-chrome" extensions for FF as well

**Comment by Te7a-Houdini** [comment]
yes i just have seen it . so maybe the port won't be that difficult

**Comment by HugoDF** [comment]
Seems to be working as is, are you happy for me to publish it to the Firefox store?

**Comment by Te7a-Houdini** [comment]
@HugoDF nice to hear that . just give it a couple of tests and when you are satisfied publish it to firefox  store,

**Comment by HugoDF** [comment]
@Te7a-Houdini as mentioned on the layout issue there was a scroll issue on FF, so I'm going ahead and implementing the same layout as Vue Devtools.

**Comment by HugoDF** [comment]
This is current master running in FF (using dev instructions), looking pretty nice. I'll give it another day or so before submitting as an official extension.

![Screen Recording 2020-04-12 at 21 11 52](https://user-images.githubusercontent.com/6459679/79078850-28235700-7d03-11ea-870e-e63406ab8237.gif)

**Comment by Te7a-Houdini** [comment]
@HugoDF ok cool :+1:

**Comment by Wulfheart** [comment]
What's the state of the firefox extension submission? This is a deal breaker for me.

**Comment by ryangjchandler** [comment]
I think it's nearly ready to be submitted to the Firefox extension store. Check with @HugoDF .

**Comment by HugoDF** [comment]
> What's the state of the firefox extension submission? This is a deal breaker for me.

Could you give it a spin using the Dev insurrections for Firefox?

I'll submit tomorrow if we don't find any issues by then

**Comment by HugoDF** [comment]
I've submitted the extension for review for inclusion on the Firefox add-on gallery

**Comment by ryangjchandler** [comment]
Nice one. Do Firefox have any way of submitting / uploading a new version via an API?

**Comment by HugoDF** [comment]
@ryangjchandler I don't believe so

The extesion is past review and available at https://addons.mozilla.org/firefox/addon/alpinejs-devtools/
