### ISSUE TITLE
Alpine.js not detected when viewing HTML file (CDN/chrome/linux)

### ISSUE THREAD

**Issue by mabdalmoniem** [Te7a-Houdini/alpinejs-devtools#47]
Environment: Google Chrome 
OS: Linux/Mint

I'm trying to play with Alpine. I'm importing it using the CDN (before closing the header tag as instructed) in an plain old HTML file, but the devtools doesn't detect any alpine component, here is a snippet of my code:

![rsz_1screenshot_from_2020-05-09_19-28-44](https://user-images.githubusercontent.com/28531841/81480772-f7640e00-922b-11ea-9024-98fb1928ad1e.png)

**Comment by HugoDF** [comment]
Is the `script` running correctly? Alpine.js detection is just "is the `Alpine` global defined?"

**Comment by HugoDF** [comment]
If you could send the HTML file's `head` that would be useful 😄

**Comment by mabdalmoniem** [comment]
Global alpine is defined, here is the `head` section

```
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Alpine.js</title>
    <style>
      .red-text {
        color: red;
      }

      .blue-text {
        color: blue;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
      defer
    ></script>
  </head>
```

**Comment by mabdalmoniem** [comment]
and here is the whole file

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Alpine.js</title>
    <style>
      .red-text {
        color: red;
      }

      .blue-text {
        color: blue;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
      defer
    ></script>
  </head>
  <body>
    <div
      x-data="{ open: false, name: 'mohamed', isRed: false }"
      x-init="() => {console.log('hello, alpine')}"
    >
      <h1 :class="{'red-text': isRed, 'blue-text': !isRed}">
        Hello, alpine.js
      </h1>

      <button @click="isRed = !isRed">change color</button>
  </body>
</html>

```

**Comment by mabdalmoniem** [comment]
and here is the whole file:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Alpine.js</title>
    <style>
      .red-text {
        color: red;
      }

      .blue-text {
        color: blue;
      }
    </style>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
      defer
    ></script>
  </head>
  <body>
    <div
      x-data="{ open: false, name: 'mohamed', isRed: false }"
      x-init="() => {console.log('hello, alpine')}"
    >
      <h1 :class="{'red-text': isRed, 'blue-text': !isRed}">
        Hello, alpine.js
      </h1>

      <button @click="isRed = !isRed">change color</button>
    </div>
  </body>
</html>

```

**Comment by HugoDF** [comment]
Thanks, I've been able to reproduce, on Chrome it's indeed not working but it's fine on Firefox...

**Comment by HugoDF** [comment]
Ok I've found the issues, not a bug, it's a configuration issue, you need to go to `about:extensions` > Alpine.js Devtools - Click Details > Allow Access to File URLs

<img width="733" alt="Screenshot 2020-05-09 at 18 58 20" src="https://user-images.githubusercontent.com/6459679/81481319-16ac6c80-9227-11ea-8222-97b56c228791.png">

If you want you can create the PR with the update to the README for this? (happy to do it myself otherwise)

**Comment by mabdalmoniem** [comment]
Thanks, It worked!
Does alpine supports named component? because the devtools now show me a component named 'div' which is a bit ambiguous IMHO, so alpine could make use of an attribute called 'name' or something which helps while debugging.

**Comment by mabdalmoniem** [comment]
Okay I'll make a pull request to update the README file

**Comment by HugoDF** [comment]
> Thanks, It worked!
> Does alpine supports named component? because the devtools now shows me a component named 'div' which is a bit ambiguous IMHO, so alpine could make use of an attribute called 'name' or something which helps while debugging.

Done as part of this issue https://github.com/Te7a-Houdini/alpinejs-devtools/issues/28 just not released yet 🙂.

I might cut a release soon, 2-3 enhancements have gone in and I wanted to get a couple more done but didn't end up having the time.

**Comment by HugoDF** [comment]
Actually while you're updating the README mind mentioning the "name" logic as per that issue?

**Comment by mabdalmoniem** [comment]
Do you mean that I should announce in the README file that soon you're gonna release an update for naming elements/components?

**Comment by HugoDF** [comment]
@mabdalmoniem well that it's done hahaha, you can just assume that by the time someone reads the README it'll be released

**Comment by mabdalmoniem** [comment]
I have updated the README, how can I make the PR? because I'm not allowed to push to the repo.
