### ISSUE TITLE
Handle component "functions" better

### ISSUE THREAD

**Issue by HugoDF** [Te7a-Houdini/alpinejs-devtools#6]
## Current behaviour

When I have a "method" on my component, it shows in the devtools as "function" and is editable (see screenshot).

<img width="368" alt="Screenshot 2020-04-12 at 15 52 01" src="https://user-images.githubusercontent.com/6459679/79071802-90f3da80-7cd5-11ea-9b43-5f5424ff92e1.png">

## Wanted behaviour

(Probably) make it read-only (and display the function body?).

**Comment by HugoDF** [comment]
@Te7a-Houdini @ryangjchandler any opinions?

I think we could do any of the following (unfortunately no equivalent Vue.js case 😄 to get inspiration from):

- make it read-only
- read-only + on expansion show its source (would have to check feasibility)
- hide it altogether (the above screenshot would only show "selectedOptions" and "options")
- hide it and put it into a separate "functions" section

**Comment by Te7a-Houdini** [comment]
@HugoDF mmmmmm i would vote for first option read-only .

**Comment by ryangjchandler** [comment]
My first opinion would be to make it read only. I'm not sure the 2nd option would be too difficult to be honest.

**Comment by HugoDF** [comment]
Displaying the function body causes extra perf overhead (in passing data to the panel), but could be toggled on by using `.toString()` on the function

**Comment by HugoDF** [comment]
Note that this hasn't been released yet.
